FROM trading-base AS builder

COPY requirements/producer.txt requirements/producer.txt
RUN uv pip install -r requirements/producer.txt

COPY . .

FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/venv /app/venv
COPY --from=builder /app/src /app/src

ENV PATH="/app/venv/bin:$PATH"
ENV PYTHONPATH=/app