services:
  db:
    image: postgres:16.4
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: [
      "postgres",
      "-c", "port=${POSTGRES_PORT}"
    ]
    networks:
      - trading_network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}", "-p", "${POSTGRES_PORT}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"


  rabbitmq:
    image: rabbitmq:4.1.0-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "5672:5672"
    networks:
      - trading_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"

  base:
    image: trading-base
    build:
      context: .
      dockerfile: docker/Dockerfile.base

  migrator:
    build:
      context: .
      dockerfile: docker/Dockerfile.migrator
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - trading_network

  producer-base:
    image: producer-base
    build:
      context: .
      dockerfile: docker/producers/Dockerfile.base
    depends_on:
      - base

  consumer:
    build:
      context: .
      dockerfile: docker/consumer/Dockerfile
    env_file: .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - trading_network

  trand:
    build:
      context: .
      dockerfile: docker/producers/Dockerfile.trand
    env_file: .env
    depends_on:
      producer-base:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - trading_network

networks:
  trading_network:
    driver: bridge

volumes:
  rabbitmq_data:
  postgres_data:
