[project]
name = "AlgoTrade"
version = "0.1.0"
description = "A set of microservices for algorithmic trading"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src"]
