FROM trading-base AS builder

COPY requirements/migrator.txt requirements/migrator.txt
RUN uv pip install -r requirements/migrator.txt

COPY . .

FROM python:3.12-slim

WORKDIR /app

COPY --from=builder /app/venv /app/venv
COPY --from=builder /app/migrations /app/migrations
COPY --from=builder /app/alembic.ini /app/alembic.ini
COPY --from=builder /app/src /app/src

ENV PATH="/app/venv/bin:$PATH"
ENV PYTHONPATH=/app

CMD ["alembic", "upgrade", "head"]