"""add manually closed field

Revision ID: c1d8e2a9f3b8
Revises: b0f7a9fe5d77
Create Date: 2025-08-21 16:43:57.697221

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1d8e2a9f3b8"
down_revision: str | None = "b0f7a9fe5d77"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deal", sa.Column("is_manually_closed", sa.Boolean(), nullable=False, server_default=sa.text("false"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deal", "is_manually_closed")
    # ### end Alembic commands ###
