"""empty message

Revision ID: b0f7a9fe5d77
Revises: aacfc5fd4609
Create Date: 2025-08-09 11:53:52.669190

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0f7a9fe5d77"
down_revision: str | None = "aacfc5fd4609"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "deal", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "deal", type_="unique")
    # ### end Alembic commands ###
