"""add sell_price field

Revision ID: d2e4f5a6b7c9
Revises: c1d8e2a9f3b8
Create Date: 2025-08-21 23:30:41.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2e4f5a6b7c9"
down_revision: str | None = "c1d8e2a9f3b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deal", sa.Column("sell_price", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deal", "sell_price")
    # ### end Alembic commands ###
