"""initial

Revision ID: aacfc5fd4609
Revises:
Create Date: 2025-05-30 09:35:34.846104

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aacfc5fd4609"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deal",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("take_profit_price", sa.Float(), nullable=True),
        sa.Column("stop_loss_price", sa.Float(), nullable=True),
        sa.Column("is_take_profit_executed", sa.Boolean(), nullable=False),
        sa.Column("is_stop_loss_executed", sa.Boolean(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("BUY", "SELL", "NOTHING", name="actionenum"),
            nullable=False,
        ),
        sa.Column("source", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deal")
    # ### end Alembic commands ###
