"""empty message

Revision ID: b0f7a9fe5d77
Revises: aacfc5fd4609
Create Date: 2025-08-09 11:53:52.669190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f7a9fe5d77'
down_revision: Union[str, None] = 'aacfc5fd4609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'deal', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deal', type_='unique')
    # ### end Alembic commands ###
